<footer>
    <div class="footer-buttons">
        <a href="mailto:info@TrueDigital.com.au" class="footer-button">Contact</a>
        <a href="https://regmasterr.atlassian.net/jira/software/projects/THED/boards/2" class="footer-button">Jira</a>
        <a href="https://github.com/RegMasterr/WebTech-Assignment-2" class="footer-button">GitHub</a>
        <a href="enhancements.php" class="footer-button">Enhancements</a> </div>
    <p class="copyright">&copy; 2025 TrueDigital Proprietary Limited</p>
</footer>