<header>
    <div class="brand">
      <img src="images/logo.png" alt="TrueDigital Logo" id="logo">
      <div class="brand-text">
        <h1><em><strong>TrueDigital</strong></em></h1>
        <p class="tagline">Powering Your Digital World</p>
      </div>
    </div>

    <nav>
      <ul class="menu">
        <li><a href="index.php" class="menu-button">Home</a></li>
        <li><a href="about.php" class="menu-button">About</a></li>
        <li><a href="jobs.php" class="menu-button">Jobs</a></li>
        <li><a href="apply.php" class="menu-button">Apply</a></li>
        <li><a href="enhancements.php" class="menu-button">Apply</a></li>
      </ul>
    </nav>
</header>